### ISSUE TITLE
Patch 3.0.0 / 3.0.1 / 3.0.2

### ISSUE THREAD

**Issue by AurelioSilver** [Xaratas/pillarsofeternity-german-patch-with-expansions#15]
Der Beta Patch ist nun verfügbar auf Steam.

Selbe Orderstruktur wie bisher. Es gibt neue Texte und Änderungen in den alten Texten.

Die Erweiterung ist noch nicht dabei.

Die deutschen Texte scheinen teilweise überarbeitet zu sein. Z.B. Änderungen von Kantor auf Sänger bei den Klassen. Wird was dauern die Unterschiede rauszusuchen und eventuell zu übernehmen.

**Comment by Xaratas** [comment]
Mit kdiff3 kann man komplette Ordnervergleiche machen, damit sollte die Gegenüberstellung einfach werden.

**Comment by AurelioSilver** [comment]
Ich nutze Winmerge. Die Unteschiede rauszufinden ist nicht das Problem. Nur sie zu bewerten und sie dann eventuell zu übernehmen. Die neuen Dateien habe ich nun schonmal importiert.

**Comment by AurelioSilver** [comment]
Also bei den Änderungen sind auch einige dabei, die ich für falsch halte.

Z.B.
data...\conversations\01_defiance_bay_copperlane\01_cv_doran.stringtable
von
 <ID>112</ID>
„Im Moment nichts.“

nach:
„Im Moment nicht.“

**Comment by Xaratas** [comment]
Hm, für sowas müsste man ja mal den ganzen Block Stringtables nachvollziehen und schauen, wer was sagt (z.B. mit dem unfertigen questeditor)

**Comment by AurelioSilver** [comment]
Ich kann Dir die ganzen Texte mal schicken. In Stronghold steward waren auch zwei Änderungen von der Sie Form nach Du. Und der Rest der Texte ist in Sie Form...

06_cv_steward in Data\06_stronghold
      <ID>195</ID>
      <DefaultText>„Lass mich mal sehen, was ich reparieren kann.“</DefaultText>
      <ID>196</ID>
      <DefaultText>„Leb wohl.“</DefaultText>

**Comment by Xaratas** [comment]
01_cv_doran gesichtet: von node 66 zu 64 oder 112 geht der Textfluss
66: Purnisc hustet, als du dich näherst. Seine Wangen sind eingefallen, seine Augen rot. "Hallo. Ich, äh ... " Er zieht die Nase hoch. "Ich habe hier einige Waren, wenn du etwas kaufen willst."
64: "Lass mich mal sehen, was du anzubieten hast."
112: "Im Moment nicht."

kann man also mitnehmen, der Text wird 3 mal verwendet, aus unterschiedlichen Freundlichkeitspfaden in der Konversation.

Das andere sind Texte die der Spieler zum Steward der Burg sagt. Und es sieht so aus, das der Spieler immer auf die höflichkeitsform verzichtet, der Steward Geist aber immer höfliche Anreden verwendet. (195 öffnet das Stronghold Menü)

**Comment by AurelioSilver** [comment]
Ok, dann wären die Änderungen richtig.

**Comment by AurelioSilver** [comment]
So, bin nun einmal durch. Englisch und Deutsch... Nun heißt es mergen, wenn ok und auf weitere Änderungen warten.

**Comment by Xaratas** [comment]
Und da kam auch schon das nächste beta Build.

**Comment by AurelioSilver** [comment]
Die Änderungen vom Final Patch 3.0 bin ich noch nicht ganz durch. data habe ich nun einmal in deutsch durch, aber den data_expansion1 Ordner noch nicht. Viele Texte von dort wurden nun in den Hauptteil verschoben...

**Comment by Xaratas** [comment]
Ich habs jetzt schonmal auf Nexus gelegt, damit unsere ~500 Nutzer was an der Hand haben.

**Comment by AurelioSilver** [comment]
Patch 3.01 ist nun da... Allerdings sind da teilweise wieder alte deutsche Texe drinnen. Einige alte Fehler sind nun wieder da und teilweise sind auch welche behoben worden. Ich gehe eh erstmal alle 3.00 Änderungen durch bevor ich mit der 3.01 anfange.

**Comment by Xaratas** [comment]
Wir scheinen uns mit einigen fehlenden Strings rumschlagen zu müssen. Siehe:
http://www.nexusmods.com/pillarsofeternity/mods/6/?tab=14&navtag=http%3A%2F%2Fwww.nexusmods.com%2Fpillarsofeternity%2Fajax%2Fmodbugs%2F%3Fid%3D6&pUp=1

Ich schau mal ob ich da was programmatisch stricken kann.

**Comment by AurelioSilver** [comment]
? Bei mir steht da 0 Bugs.

**Comment by Xaratas** [comment]
Hab den schon abgehandelt und geschlossen, siehe commit hier. Könnte sein, das der Private ist und du den deswegen nicht siehst.

Mein Sripting Foo hat mir gesagt, das etwa 500 bis 2000 Strings nicht übersetzt sind, hab das aber noch nicht in einer Form, mit der man arbeiten kann.

**Comment by AurelioSilver** [comment]
Hm, ok. Werde dann die Tage mir die 3.01 ansehen. Eine 3.02 steht wohl auch bald an...
Danach schaue ich mir die neue Erweiterung an. 

Das aber so viele Strings fehen sollen?

**Comment by Xaratas** [comment]
Ich bin mir da noch nicht sicher, welche von denen die nicht übersetzt sind wirklich zur anzeige kommen. Das seh ich momentan noch nicht, vermute aber das da einiges in Soundsets hängen bleibt.

**Comment by Xaratas** [comment]
Vermutlich sind das allerhöchstens freischwebende Texte.
conversations\07_gilded_vale\07_bs_torture
conversations\bs_greetings
conversations\db_ambients_all
conversations\te_barks_all
conversations\db_barks_all
conversations\te_ambients_all

Hier gibts wenige fehlende Texte
1: conversations\companions\poi\cm_poi_ogre_bones
<ID>3</ID>^M                                                                                            |       <ID>3</ID>
      <DefaultText>"Someone's a messy eater."</DefaultText>^M

6: conversations\03_defiance_bay_ondra_gift\03_cv_lurgolder
~150: conversations\00_dyrwood\00_cv_nyfre
6: conversations\00_dyrwood\00_si_cliaban_water_tunnel_02
13: conversations\00_dyrwood\00_cv_nyfre_medreth_01
3: conversations\00_dyrwood\00_harond_intro

Das meiste ist glücklicherweise in sich zusammengefallen, viel Voiceset, viel Debug, viele Nodes ohne darstellenden Text. Nur Nyfre fällt auf, ist der NPC aus dem Spiel genommen worden? Scheinbar trifft ja keiner auf den, sonst hätte sich schon wer beschwert.

war jetzt nur der data Ordner.

**Comment by AurelioSilver** [comment]
Also die Änderungen von 3.01 durchzugehen ist echt mühsam... Soviele alte und neue Fehler drinnen und dann wieder gute Korrekturen...

**Comment by Xaratas** [comment]
conversations/00_dyrwood/00_cv_lord_harond.stringtable 

Könnten da female Texts mit "Mein Fürst …" falsch sein? Seh ich grad beim rumtesten mit den Dateien.

**Comment by AurelioSilver** [comment]
259 - 265 ? Keine Ahnung. In der engischen Version gibt es da nicht.. Ausser bei 263... Aber da ist der Text identisch...

**Comment by Xaratas** [comment]
Ok, im Forum sagt Aarik, dass das nicht übersetzte Zeug nicht verwendet wird.
Im WM2 hab ich jetzt noch einige Einzeltexte die wahrscheinlich doch fehlen, die mach ich mal morgen Abend, jetzt ist spät genug.

**Comment by AurelioSilver** [comment]
So, neuer Beta Patch ist da. Sind wieder einige Änderungen da. Werde mich bei Gelegenheit wieder ransetzen. Schaue aber noch, ob Cynthel Natal nun mit Git zurecht kommt oder nicht, bevor ich ihre Änderungen übernehme.

**Comment by Cynthel-Natal** [comment]
Ich glaub, langsam krieg ich den dreh raus. ^^

**Comment by AurelioSilver** [comment]
Patch 3.0.2 Beta 2 nun da. Keine Änderungen bei den englischen Texten. Zwei minimale Änderungen bei den deutschen.

**Comment by Xaratas** [comment]
Das ist ja regelrecht übersichtlich.

**Comment by Xaratas** [comment]
Und da gabs ein Release, mal schauen ob da noch was dabei ist.

**Comment by AurelioSilver** [comment]
So wie ich es sehe, ist da keine Änderung zur Beta Version. Wenn wir noch die fehlenden Übersetzungen nachreichen, könnte man noch einen Release bauen. Oder kommen noch von uns Änderungen? So viele waren es ja bisher nicht.

**Comment by Xaratas** [comment]
Ne, ich würd sagen momentan ist nichts weiter auf der Liste. Kann dann raus.

**Comment by AurelioSilver** [comment]
Zwei Textzeilen müssen noch übersetzt werden. CN wollte das machen. Muss nur ihr Git noch fixen.
