### ISSUE TITLE
Expansion 2

### ISSUE THREAD

**Issue by AurelioSilver** [Xaratas/pillarsofeternity-german-patch-with-expansions#21]
Ist nun auch draussen.

Es gibt nun einen neuen Ordner: data_expansion2

**Comment by Xyarvius** [comment]
Hey, ich würde euch gerne beim Aktualisieren helfen. Im Wiki stehen wohl alle wichtigen Infos die ich brauche. Ich nutze GitHub Desktop. Was wäre eine gute Software um Dateien/Dateistrukturen auf Unterschiede zu vergleichen? Falls ihr meine Hilfe brauchen könnt, könnt ihr mir ja Instruktionen geben, was ich tun kann, damit ich euch nicht ins Handwerk pfusche.

**Comment by AurelioSilver** [comment]
Welches OS nutzt Du? Ich habe selber Windows und nutze Winmerge und Notepad++ als Editor.

Aktuell bin ich an der Hauptversion also dem data Ordner dran. Danach dem data_expansion1.

Ich weiss nicht, woran Xaratas arbeiten will, aber aktuell würde ich sagen, wenn sich einer um data_expansion2 kümmern kann, würde das helfen.

**Comment by Xyarvius** [comment]
Ich nutze ebenfalls Windows und Notepad++ hab ich auch auf der Platte.
Dann versuche ich mich mal an data_expansion2.

**Comment by AurelioSilver** [comment]
Ok, da musst Du erstmal nur die neuen Dateien importieren.

Dann geht es daran die "" umzuwandeln, etc... Die Übersetzungen anzupassen und unsere Texte aus den data und data_expansion1 eventuell zu importieren. Einige Texte kommen manchmal doppelt vor. Die sollten dann natürlich alle gleich sein.

**Comment by Xyarvius** [comment]
Alles klar. An der Stelle gleich mal eine Verständnisfrage: z.B. steht in der deutschen Datei von 06_cv_visitor_cruel_lord:

`<DefaultText />`

und in der englischen:

`<DefaultText>Script Node 59</DefaultText>`

Sollen solche Zeilen dann ins Deutsche vom Englischen direkt so übernommen werden?

**Comment by AurelioSilver** [comment]
Kann, muss aber nicht. Solche Sachen werden nicht dargestellt. Bei <DefaultText /> im deutschen Text greift dann vermutlich die englische Variante.

**Comment by Xyarvius** [comment]
Ok, ich merke, es kommen mehr und mehr Fragen auf. z.B. wie ich bestimmte fehlende Worte übersetze damit es einheitlich ist (z.B. lord und m'lady).

Daher würde ich mich erst einmal darauf fokusieren, alle "" in „“ umzuwandeln und bei doppelten Texten, eure Texte zu importieren, da dürften keine Unklarheiten aufkommen, wenn das in eurem Sinne ist.

**Comment by AurelioSilver** [comment]
Ja, das ist erstmal ein guter Anfang.

**Comment by Xaratas** [comment]
Expansion 2 haben wir jetzt drin, mach ich mal zu.
