### ISSUE TITLE
Gestaltwandler / Geisterwandler

### ISSUE THREAD

**Issue by AurelioSilver** [Xaratas/pillarsofeternity-german-patch-with-expansions#40]
Spiritshift wird teilweise unterschiedlich übersetzt. Mal ist es Gestaltwandler dann wieder Geisterwandler.

Siehe z.B. abilities

1508
Geisterwandler
Spiritshift

1487
Hinweis: Leid des Novizen betrifft nicht die Gestaltwandelform des Druiden.
Note: Novice's Suffering does not apply to a druid's Spiritshift form.

Geisterwandler wird wohl öfters genommen. Auf was einigen wir uns?

**Comment by Xaratas** [comment]
Geisterwandler ist von den Professionellen Übersetzern. Gestaltwandler von uns. Da es beim Druiden im Bezug auf PoE grade um die körperliche Veränderung geht bevorzuge ich Gestaltwandler.
