### ISSUE TITLE
Beta Patch 3.0.4

### ISSUE THREAD

**Issue by AurelioSilver** [Xaratas/pillarsofeternity-german-patch-with-expansions#46]
Geplant für 4.10.2016.

Mal schauen, welche Änderungen nötig sind.

**Comment by AurelioSilver** [comment]
Hm, bis auf eine leere neue ID alles identisch,

**Comment by AurelioSilver** [comment]
Die ID hat nun Inhalt sonst ist nichts mehr hinzugekommen in Beta 2.

**Comment by Xaratas** [comment]
Dann wirds wohl nichts mehr geben von offizieller Seite aus.

**Comment by AurelioSilver** [comment]
Kannst dann mergen? Und kommt noch was von Deiner Seite? Noch mehr Word? Wir könnten auch mal anfragen, ob sie unsere Übersetzung übernehmen wollen.

**Comment by Xaratas** [comment]
Mehr Word könnte man machen, aber da hab ich gerade nicht den Elan für. Nen Anfrageversuch kann man allerdings nochmal unternehmen.

**Comment by AurelioSilver** [comment]
Ok, kann ich verstehen. :)

**Comment by AurelioSilver** [comment]
Patch ist nun live. Keine weiteren Änderungen. Kannst dann noch Nexus aktualisieren?

**Comment by Xaratas** [comment]
Ist auf Nexus.
