### ISSUE TITLE
Neues Addon

### ISSUE THREAD

**Issue by AurelioSilver** [Xaratas/pillarsofeternity-german-patch-with-expansions#55]
https://eternity.obsidian.net/eternity/news/pillars-of-eternity-definitive-edition-arrives-november-15th-for-pc-mac-and-linux

**Comment by Xaratas** [comment]
Da muss man sich ja glatt mal bereit halten und ein Release zusammenpacken. (Und mind. 2 neue GB in die POE Linux Partition bringen …)

**Comment by AurelioSilver** [comment]
Naja, schauen wir mal, wie umfangreich das wird... Und ob die auch die Unity Version anheben. Für die Konsolen Version werden sie es vermutlich gemacht haben.

**Comment by Xaratas** [comment]
Die doch „umfangreichen“ Patchnotes sagen es gibt einige neue Items und somit neue Texte. 
Download läuft.

**Comment by AurelioSilver** [comment]
Ok, ich bin mit den Änderungen durch. War nicht so viel. Neue Unity Version gab es auch nicht. :/

**Comment by Xaratas** [comment]
Dann werd ich das morgen mal einpacken und hochladen.

**Comment by AurelioSilver** [comment]
Ok, prima.
